sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t dsouzareuben79964/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dsouzareuben79964/docker-react npm run test

deploy:
   provider: elasticbeanstalk
   region: "eu-north-1"
   app: "docker-project"
   env: "Docker-project-env"
   bucket_name: "elasticbeanstalk-eu-north-1-604863143682"
   bucket_path: "docker-project"
   on:
      branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key: "$AWS_SECRET_KEY"
